spring:
  application:
    name: Assignment

  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  h2:
    console:
      enabled: true

#api:
#  security:
#    ignored:  /api/users/**, /api/users, /api/balance, /api/transaction, /h2-console, /api/user/create

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

jwt:
  secret: ${JWT_KEY}
  expiration: ${JWT_EXPIRY}
