spring:
  datasource:
    url: jdbc:h2:mem:bank;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: test
    password: test
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
#  h2:
#    console:
#      enabled: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

jwt:
  secret: UGEzLf3ug6HdJy7nEaVZjIxraYsbNIbt4AIBpgTAgTQ=
  expiration: 5000000

logging:
  level:
    root: INFO
  file:
    name: target/tests.log

